name: Deploy to Azure Web App

on:
  workflow_dispatch:
    inputs:
      landing_page_only:
        description: 'Deploy landing page only'
        required: false
        default: 'false'

  push:
    branches:
      - main
      - develop
      - 'release/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'PRD' || github.ref == 'refs/heads/develop' && 'DEV' || 'UAT' }}

    steps:
      - uses: actions/checkout@v4

      # 🔥 LANDING MODE
      - name: Prepare landing page
        if: ${{ github.event.inputs.landing_page_only == 'true' }}
        run: |
          mkdir deploy-package
          cp landing.html deploy-package/index.html

      - name: Deploy landing page
        if: ${{ github.event.inputs.landing_page_only == 'true' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: devops-practice-ilyas
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: deploy-package

      # 🔥 NORMAL FLOW
      - name: Setup Node
        if: ${{ github.event.inputs.landing_page_only != 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install
        if: ${{ github.event.inputs.landing_page_only != 'true' }}
        run: npm install

      - name: Build
        if: ${{ github.event.inputs.landing_page_only != 'true' }}
        run: npm run build

      - name: Deploy App
        if: ${{ github.event.inputs.landing_page_only != 'true' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: devops-practice-ilyas
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: .