name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
      - develop
      - 'release/*'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 🔥 Environment mapping
    environment: ${{ github.ref == 'refs/heads/main' && 'PRD' || github.ref == 'refs/heads/develop' && 'DEV' || 'UAT' }}

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 3. Install
      - name: Install dependencies
        run: npm install

      # 4. Build
      - name: Build
        run: npm run build

      # 5. Deploy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: rg-devops-practice   # ⚠️ apna exact naam daalo
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: .